- name: Update node-exporter
  hosts: node_exporter
  become: true
  gather_facts: false

  vars:
    node_exporter_action: "restarted"  # Bisa diubah ke 'stopped', 'started', atau 'restarted'
    node_exporter_version: "1.9.1"
    download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    archive_name: "node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    extract_dir: "node_exporter-{{ node_exporter_version }}"
    dest_dir: "/home/{{ ansible_user }}"  # Hindari hardcoded path jika tidak ada gather_facts

  vars_files:
    - ../vault.yaml

  tasks:
    - name: Set sudo password per-host
      set_fact:
        ansible_become_pass: "{{ lookup('vars', 'become_pass_' + inventory_hostname) }}"

    - block:

        - name: Download node_exporter
          get_url:
            url: "{{ download_url }}"
            dest: "{{ dest_dir }}/{{ archive_name }}"
            mode: '0644'
            force: no

        - name: Extract node_exporter archive
          unarchive:
            src: "{{ dest_dir }}/{{ archive_name }}"
            dest: "{{ dest_dir }}"
            remote_src: yes
            creates: "{{ dest_dir }}/{{ extract_dir }}/node_exporter"

        - name: Replace binary node_exporter ke /usr/local/bin
          copy:
            src: "{{ dest_dir }}/{{ extract_dir }}.linux-amd64/node_exporter"
            dest: /usr/local/bin/node_exporter
            mode: '0755'
            remote_src: yes
            force: yes

        - name: Restart node_exporter service
          systemd:
            name: node_exporter
            state: "{{ node_exporter_action }}"
            enabled: yes

        - name: Hapus file arsip node_exporter
          file:
            path: "/home/{{ ansible_user }}/{{ archive_name }}"
            state: absent
          when: node_exporter_action == 'restarted'

        - name: Hapus folder hasil extract node_exporter
          file:
            path: "/home/{{ ansible_user }}/node_exporter-{{ node_exporter_version }}.linux-amd64"
            state: absent
          when: node_exporter_action == 'restarted'

        - name: Kirim pesan ke Telegram jika berhasil
          uri:
            url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
            method: POST
            body_format: json
            headers:
              Content-Type: "application/json"
            body:
              chat_id: "{{ telegram_chat_id }}"
              text: "✅ SUKSES: Node Exporter berhasil di update ke versi {{ node_exporter_version }} di host {{ inventory_hostname }}"
              parse_mode: "Markdown"
          delegate_to: localhost
          become: false

      rescue:
        - name: Kirim pesan ke Telegram jika GAGAL
          uri:
            url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
            method: POST
            body_format: json
            headers:
              Content-Type: "application/json"
            body:
              chat_id: "{{ telegram_chat_id }}"
              text: "❌ GAGAL: Ansible gagal update Node Exporter ke versi {{ node_exporter_version }} di host {{ inventory_hostname }}"
              parse_mode: "Markdown"
          delegate_to: localhost
          become: false
